//Blacklist Items
blacklisted_bag = [
	"Afghan_01Hat",
	"Afghan_02Hat",
	"Afghan_03Hat",
	"Afghan_04Hat",
	"Afghan_05Hat",
	"Afghan_06Hat",
	"U_Afghan01",
	"U_Afghan01NH",
	"U_Afghan02",
	"U_Afghan02NH",
	"U_Afghan03",
	"U_Afghan03NH",
	"U_Afghan04",
	"U_Afghan05",
	"U_Afghan06",
	"U_Afghan06NH"
];

blacklisted_weapon = [
	"Ibex_TSS",
	"Ibex_TSSD",
	"PAS18_ej",
	"PAS18D_ej",
	"ej_launch_TitanDAT",
	"ej_launch_TitanAAD"	
];

whitelisted_from_arsenal = [
	"MineDetector",
	"Binocular",
	"Rangefinder",
	"ItemCompass",
	"ItemGPS",
	"ItemMap",
	"ItemRadio",
	"ItemWatch",
	"HandGrenade",
	"MiniGrenade",
	"Laserbatteries",
	"optic_LRPS",
	"optic_AMS",
	"optic_AMS_snd",
	"optic_Arco",
	"optic_Arco_blk_F",
	"optic_DMS_weathered_F",
	"APERSMine_Range_Mag",
	"APERSTripMine_Wire_Mag",
	"APERSBoundingMine_Range_Mag",
	"ATMine_Range_Mag",
	"SatchelCharge_Remote_Mag",
	"DemoCharge_Remote_Mag",
	"SLAMDirectionalMine_Wire_Mag",
	"ClaymoreDirectionalMine_Remote_Mag",
	"launch_MRAWS_green_F",
	"launch_B_Titan_F",
	"launch_I_Titan_F",
	"launch_O_Titan_F",
	"launch_B_Titan_short_F",
	"launch_I_Titan_short_F",
	"launch_O_Titan_short_F",
	"arifle_RPK12_F",
	"srifle_DMR_01_F"
];
