//Blacklist Items
blacklisted_bag = [
];

blacklisted_weapon = [
	"CUP_PylonPod_",
	"CUP_optic_CWS",
	"CUP_optic_AN_PAS_13c1",
	"CUP_optic_AN_PAS_13c2",
	"CUP_optic_GOSHAWK",
	"CUP_optic_GOSHAWK_RIS",
	"CUP_Item_optic_AN_PAS_13c2",
	"CUP_Item_optic_AN_PAS_13c1",
	"_Gun_Bag",
	"_Pod_",	
	"Bipod_Bag",
	"Tripod_Bag",
	"TripodHigh_Bag",
	"TripodLow_Bag"
];

whitelisted_from_arsenal = [

// Belka Faction items
// Uniform
"BLK_Uniform_Flecktarn_1",
"BLK_Uniform_Flecktarn_2",
"BLK_Uniform_Flecktarn_3",
"BLK_Uniform_Flecktarn_4",
"BLK_Uniform_Flecktarn_5",
"BLK_Uniform_Flecktarn_6",
"BLK_Uniform_Flecktarn_7",
"BLK_Uniform_Flecktarn_8",
"BLK_Uniform_Tropentarn_1",
"BLK_Uniform_Tropentarn_2",
"BLK_Uniform_Tropentarn_3",
"BLK_Uniform_Tropentarn_4",
"BLK_Uniform_Tropentarn_5",
"BLK_Uniform_Tropentarn_6",
"BLK_Uniform_Tropentarn_7",
"BLK_Uniform_Tropentarn_8",
"BLK_Uniform_Nordtarn",
"BLK_Uniform_shortsleeve_Nordtarn",
"BLK_Uniform_Shirt_Nordtarn",
"BLK_Uniform_Overalls",
"BLK_Uniform_Pilot_Overalls",
"BLK_Uniform_pullover_Nordtarn",
"BLK_Uniform_Olive_Drab",
"BLK_Uniform_Olive_Drab_Gloves",
"BLK_Uniform_Olive_Drab_Rolled",
"BLK_Uniform_Olive_Drab_Rolled_Gloves",
"BLK_Stealth_Uniform_Multitarn",
"BLK_Stealth_Uniform_Rolled_Multitarn",
"BLK_Uniform_Wintertarn_suit",
// Backbag
"BLK_B_AssaultPack_Multitarn",
"BLK_B_AssaultPack_Enhanced_Multitarn",
"BLK_B_Kitbag_Multitarn",
"BLK_B_RadioBag_Flecktarn",
"BLK_B_RadioBag_Multitarn",
"BLK_B_RadioBag_Nordtarn",
"BLK_B_RadioBag_Olive_Drab",
"BLK_B_RadioBag_Troppentarn",
"BLK_B_RadioBag_Wintertarn",
"BLK_B_Pack_Nordtarn",
"BLK_B_Pack_Wintertarn",
// Helmet
"BLK_H_",
// Weapon
"AC_BLK_weapon_",

	"MineDetector",
	"Binocular",
	"Rangefinder",
	"ItemCompass",
	"ItemGPS",
	"ItemMap",
	"ItemRadio",
	"ItemWatch",
	"HandGrenade",
	"MiniGrenade",
	//"Laserbatteries",
	//"APERSMine_Range_Mag",
	//"APERSBoundingMine_Range_Mag",
	"ATMine_Range_Mag",
	"SatchelCharge_Remote_Mag",
	"SLAMDirectionalMine_Wire_Mag",
	// Z@Warrior
	"optic_Aco",
	"optic_Arco",
	"optic_LRPS",
	"optic_Holosight",
	"optic_SOS",
	"optic_MRCO",
	"optic_Hamr",
	"muzzle_snds_M",
	"muzzle_snds_B",
	"muzzle_snds_B_khk_F",
	"acc_pointer_IR",
	"acc_flashlight",
	"bipod_01_F_khk",
	"bipod_02_F_blk",
	"bipod_01_F_blk",
	// Granaten
	"SmokeShellBlue",
	"SmokeShellYellow",
	"SmokeShellGreen",
	"SmokeShellOrange",
	"SmokeShellRed",
	"SmokeShellPurple",
	"SmokeShell",
	"Chemlight_red",
	"Chemlight_green",
	"Chemlight_yellow",
	"Chemlight_blue",
	"1Rnd_HE_Grenade_shell",
	// Sprengmittel
	"DemoCharge_Remote_Mag",
	"APERSMine_Range_Mag",
	"ClaymoreDirectionalMine_Remote_Mag",
	// under Water equipment
	"U_B_Wetsuit",
	"V_RebreatherB",
	"G_B_Diving",
	"arifle_SDAR_F",
	"20Rnd_556x45_UW_mag"
];