// *** CIVILIAN ***

civilians = [
	"CFP_C_ASIA_Civilian_2_01",
	"CFP_C_ASIA_Civilian_3_01",
	"CFP_C_ASIA_Civilian_4_01",
	"CFP_C_ASIA_Civilian_5_01",
	"CFP_C_ASIA_Civilian_6_01",
	"CFP_C_ASIA_Civilian_7_01",
	"CFP_C_ASIA_Civilian_8_01",
	"CFP_C_ASIA_Civilian_9_01",
	"CFP_C_ASIA_Civilian_10_01",
	"CFP_C_ASIA_Civilian_11_01",
	"CFP_C_ASIA_Civilian_12_01"
];

civilian_vehicles = [
	"C_Quadbike_01_F",
	"CUP_C_A300_CIV",
	"CUP_C_B737_CIV",
	"CUP_C_Cessna_172_CIV-BLUE",
	"CFP_C_ASIA_UAZ_01",
	"CFP_C_ASIA_Ural_01",
	"CFP_C_ASIA_SUV_01",
	"CFP_C_ASIA_Skoda_Octavia_01",
	"CFP_C_ASIA_Praga_V3S_01",
	"CFP_C_ASIA_Offroad_01",
	"CFP_C_ASIA_MB_4WD_01",
	"CFP_C_ASIA_Land_Rover_01",
	"CFP_C_ASIA_Datsun_Pickup_01",
	"CFP_C_ASIA_Water_Scooter_01",
	"CFP_C_ASIA_Fishing_Boat_01",
	"C_Offroad_01_covered_F",
	"C_Offroad_01_comms_F",
	"I_C_Offroad_02_unarmed_F",
	"C_Quadbike_01_F",
	"SUV_01_base_black_F",
	"C_SUV_01_F",
	"C_Van_01_transport_F",
	"C_Van_01_box_F",
	"C_Van_01_fuel_F",
	"C_Quadbike_01_F",
	"C_Van_02_transport_F",
	"C_Van_02_medevac_F",
	"C_Van_02_service_F",
	"B_GEN_Van_02_transport_F",
	"C_Truck_02_covered_F",
	"C_Truck_02_transport_F",
	"C_Tractor_01_F",
	"C_Tractor_01_F"
];
