LRX_mod_list_name = [
    ["3AS_KF", "3AS Project Knightfall", EAST],
    ["3CB_BAF_D", "3CB British Army Desert", WEST],
    ["3CB_BAF_W", "3CB British Army Woodland", WEST],
    ["3CB_ChDKZ", "3CB Chernarussian Red Star", EAST],
    ["3CB_ION_IND", "3CB ION Services - Urban", WEST],
    ["3CB_LDF_OPF", "3CB Livonia Defence Force", EAST],
    ["3CB_ISIS_OPF", "3CB ISIS Group", EAST],
    ["3CB_MDF_OPF", "3CB Malden Defence Force", EAST],
    ["3CB_TNA_OPF", "3CB Takistan National Army", EAST],
    ["ACR_A3", "Army of the Czech Republic", WEST],
    ["AMF_BLU", "AMF French Forces", WEST],
    ["AMF_R3F_D", "AMF R3F French Forces - Desert", WEST],
    ["AMF_R3F_W", "AMF R3F French Forces - Woodland", WEST],
    ["ASZ_ITALY", "ASZ Italian Army", WEST],
    ["BW_MOD", "Bundenswehr Tropentarn", WEST],
    ["CFP_B_ILIDF", "CFP Israeli Defence Force", WEST],
    ["CFP_O_HAMAS", "CFP Hamas Group", EAST],
    ["CFP_O_HEZBOLLAH", "CFP Hezbollah Group", EAST],
    ["CFP_O_IQARMY", "CFP Iraq Army", EAST],
    ["CFP_O_NKARMY", "CFP North Korea Army", EAST],
    ["CFP_O_SYARMY", "CFP Syrian Army", EAST],
    ["CFP_Sudan", "Sudan Rebel", EAST],
    ["CP_AFRF", "CUP AFRF Modern MSV", EAST],
    ["CP_AFU", "CUP Armed Forces of Ukraine", WEST],
    ["CP_BAF_DES", "CUP BAF Desert", WEST],
    ["CP_BELKA_D", "CUP Belka Desert", EAST],
    ["CP_BELKA_W", "CUP Belka Woodland", EAST],
    ["CP_BELKA_WI", "CUP Belka Winter", EAST],
    ["CP_BW_W", "CUP NATO (US,BAF,BW", WEST],
    ["CP_ION_WI", "CUP ION PMC Winter", WEST],
    ["CP_MAF", "CUP Mexican Armed Forces", WEST],
    ["CP_SAHRA_D", "CUP Royal Army Corps", WEST],
    ["CP_PLA", "CUP People's Liberation Army", EAST],
    ["CP_TA", "CUP Takistan", EAST],
    ["CP_USMC_D", "CUP USMC Desert", WEST],
    ["CP_USMC_W", "CUP USMC Woodland", WEST],
    ["CWR3_BAF", "Cold War Rearmed - BAF", WEST],
    ["CWR3_FIA", "Cold War Rearmed - FIA", WEST],
    ["CWR3_SOV", "Cold War Rearmed - SOVIET", EAST],
    ["CWR3_TDF", "Cold War Rearmed - TONALI", WEST],
    ["CWR3_USA", "Cold War Rearmed USA", WEST],
    ["DEV_TAF", "Turkish Army Force", WEST],
    ["DKOK", "Death Korps Of Kreig", WEST],
    ["EAW_IJA", "Imperial Japanese Army", WEST],
    ["EAW_NRA", "NRA", WEST],
    ["EJW_TA", "EJW Taliban", EAST],
    ["EJW_TF", "EJW Task Force", WEST],
    ["FFAA_SPAIN_W", "FFAA SPAIN Woodland", WEST],
    ["GM_EAST_WINT", "Global Mob. EAST Winter", EAST],
    ["GM_EAST", "Global Mob. EAST", EAST],
    ["GM_WEST_WINT", "Global Mob. WEST Winter", WEST],
    ["GM_WEST", "Global Mob. WEST", WEST],
    ["IC_AFMC", "CSLA Armed Forces of the Midland Coalition", WEST],
    ["IC_CSLA", "CSLA Czechoslovak People's Army", EAST],
    ["IC_US85", "CSLA US Army", WEST],
    ["GX_Cartel", "GX Blanco Cartel", EAST],
    ["IFA_REDARMY_W", "IFA Red Army Winter", EAST],
    ["IFA_REDARMY", "IFA Red Army", EAST],
    ["IFA_USARMY", "IFA US Army ", WEST],
    ["IFA_WEHRM_W", "IFA Wehrmacht Winter", WEST],
    ["IFA_WEHRM", "IFA Wehrmacht", WEST],
    ["IRI_IRAN", "Iran", INDEPENDENT],
    ["JELY_BLU", "JELY BLU", WEST],
    ["JELY_RED", "JELY RED", EAST],
    ["ML700_Imperials", "Imperials", WEST],
    ["NF_FINNISH", "Finnish", WEST],
    ["OPTRE_COV", "OPTRE-FC Covenant", EAST],
    ["OPTRE_UNSC", "OPTRE-FC UNSC", WEST],
    ["OPTRE", "Operation Trebuchet", WEST],
    ["PO_SA", "Project Opfor Sahrani Army", EAST],
    ["PO_TA", "Project Opfor Takistani Army", EAST],
    ["PO_UAF", "Project Opfor Ukrainian Army", EAST],
    ["R3F_WEST_D", "R3F WEST Desert", WEST],
    ["R3F_WEST_W", "R3F WEST Woodland", WEST],
    ["RHS_AFRF", "RHS AF Russian Fed.", EAST],
    ["RHS_RACS", "RHS RACS (Royal Army Corps Sahrani)", WEST],
    ["RHS_SLA", "RHS SLA (Sahrani Liberation Army)", EAST],
    ["RHS_UFP", "RHS UFP (Ukrainian Factions Project)", WEST],
    ["RHS_USAF", "RHS US Armed Force", WEST],
    ["RHS_SAF", "RHS Serbian Armed Forces", WEST],
    ["RHS_SVK_BW", "RHS Slovak Armed Forces", WEST],
    ["ROAF_BLU", "Romanian Armed Forces", WEST],
    ["RUS_GRU", "Russian Armed Forces 2035", EAST],
    ["Ryan_ZD", "Ryan Zombies and Demons", INDEPENDENT],
    ["SAF2035", "South African Armed Forces", WEST],
    ["SFP_SAF", "Swedish armed Forces", WEST],
    ["SOG_USA", "SoG Prairie Fire USA", WEST],
    ["SOG_VIETCONG", "SoG Prairie Fire VIETCONG", EAST],
    ["SPE_FFI", "SPE - FFI Force Interieur", INDEPENDENT],
    ["SPE_FR", "SPE - FR Liberation Army", INDEPENDENT],
    ["SPE_GER", "SPE - GER Wehrmacht", WEST],
    ["SPE_US", "SPE - USA US Army", INDEPENDENT],
    ["SW_TOR", "Star Wars The Old Republic", WEST],
    ["TFM_MSLI_D", "Milsim Light Infantry - Desert", WEST],
    ["TFM_MSLI_W", "Milsim Light Infantry - Woodland", WEST],
    ["TFM_MSCA_D", "Milsim Combined Arms - Desert", WEST],
    ["TFM_MSCA_W", "Milsim Combined Arms - Woodland", WEST],
    ["TFM_SOG_CA", "SOG US for Combined Arms", WEST],
    ["TFM_SOG_LI", "SOG US for Light Infantry", WEST],
    ["TIOW_CSP", "Chaos Space Marines", EAST],
    ["TIOW_TAU", "Tau Alliance", EAST],
    ["UA_AZOV", "Armed Forces of Ukraine", WEST],
    ["UNS_NVA", "Unsung NVA", EAST],
    ["UNS_US", "Unsung USA", WEST],
    ["VME_CHINA", "VME China Army", WEST],
    ["VTF_KDF", "Korsac Defense Force", WEST],
    ["VTF_KI", "Korsac Insurgents", EAST],
    ["WBK_ORKS", "Orks", EAST],
    ["WS_FIA", "West Sahara FIA", EAST],
	["WS_UNA", "West Sahara UNA", WEST]
];
