LRX_mod_list_name = [
	["3AS_KF", "3AS Project Knightfall"],
	["3CB_BAF_D", "3CB British Army Desert"],
	["3CB_BAF_W", "3CB British Army Woodland"],
	["3CB_ChDKZ", "3CB Chernarussian Red Star"],
	["3CB_ION_IND","3CB ION Services - Urban"],
	["3CB_LDF_OPF","3CB Livonia Defence Force"],
	["3CB_MDF_OPF","3CB Malden Defence Force"],
	["3CB_TNA_OPF","3CB Takistan National Army"],
	["ACR_A3", "Army of the Czech Republic"],
	["AMF_BLU", "AMF French Forces"],
	["AMF_R3F_D", "AMF R3F French Forces - Desert"],
	["AMF_R3F_W", "AMF R3F French Forces - Woodland"],	
	["ASZ_ITALY", "ASZ Italian Army"],
	["BW_MOD", "Bundenswehr Tropentarn"],
	["CFP_B_ILIDF","CFP Israeli Defence Force"],
	["CFP_O_HAMAS", "CFP Hamas"],
	["CFP_O_HEZBOLLAH", "CFP Hezbollah"],
	["CFP_O_IQARMY", "CFP Iraq Army"],
	["CFP_O_NKARMY","CFP North Korea Army"],
	["CFP_O_SYARMY", "CFP Syrian Army"],
	["CFP_Sudan", "Sudan"],
	["CP_AFRF", "CUP AFRF Modern MSV"],
	["CP_AFU", "CUP Armed Forces of Ukraine"],
	["CP_BAF_DES", "CUP BAF Desert"],
	["CP_BELKA_D", "CUP Belka Desert"],
	["CP_BELKA_W", "CUP Belka Woodland"],
	["CP_BELKA_WI", "CUP Belka Winter"],
	["CP_BW_W", "CUP NATO (US,BAF,BW"],
	["CP_ION_WI", "CUP ION PMC Winter"],
	["CP_MAF", "CUP Mexican Armed Forces"],
	["CP_SAHRA_D", "CUP Royal Army Corps"],
	["CP_TA", "CUP Takistan"],
	["CP_USMC_D", "CUP USMC Desert"],
	["CP_USMC_W", "CUP USMC Woodland"],
	["CWR3_BAF", "Cold War Rearmed - BAF"],
	["CWR3_FIA", "Cold War Rearmed - FIA"],
	["CWR3_SOV", "Cold War Rearmed - SOVIET"],
	["CWR3_TDF", "Cold War Rearmed - TONALI"],
	["CWR3_USA", "Cold War Rearmed USA"],
	["DEV_TAF", "Turkish Army Force"],
	["DKOK", "Death Korps Of Kreig"],
	["EAW_IJA", "Imperial Japanese Army"],
	["EAW_NRA", "NRA"],
	["EJW_TA", "EJW Taliban"],
	["EJW_TF", "EJW Task Force"],
	["FFAA_SPAIN_W", "FFAA SPAIN Woodland"],
	["GM_EAST_WINT", "Global Mob. EAST Winter"],
	["GM_EAST", "Global Mob. EAST"],
	["GM_WEST_WINT", "Global Mob. WEST Winter"],
	["GM_WEST", "Global Mob. WEST"],
	["GX_Cartel","GX Blanco Cartel"],
	["IFA_REDARMY_W", "IFA Red Army Winter"],
	["IFA_REDARMY", "IFA Red Army"],
	["IFA_USARMY", "IFA US Army "],
	["IFA_WEHRM_W", "IFA Wehrmacht Winter"],
	["IFA_WEHRM", "IFA Wehrmacht"],
	["IRI_IRAN", "Iran"],
	["JELY_BLU", "JELY BLU"],
	["JELY_RED", "JELY RED"],
	["ML700_Imperials", "Imperials"],
	["NF_FINNISH", "Finnish"],
	["OPTRE_COV", "OPTRE-FC Covenant"],
	["OPTRE_UNSC", "OPTRE-FC UNSC"],
	["OPTRE", "Operation Trebuchet"],
	["PO_SA", "Project Opfor Sahrani Army"],
	["PO_TA", "Project Opfor Takistani Army"],
	["PO_UAF", "Project Opfor Ukrainian Army"],
	["R3F_WEST_D", "R3F WEST Desert"],
	["R3F_WEST_W", "R3F WEST Woodland"],
	["RHS_AFRF", "RHS AF Russian Fed."],
	["RHS_RACS", "RHS RACS (Royal Army Corps Sahrani)"],
	["RHS_SLA", "RHS SLA (Sahrani Liberation Army)"],
	["RHS_UFP", "RHS UFP (Ukrainian Factions Project)"],
	["RHS_USAF", "RHS US Armed Force"],
	["RHS_SVK_BW", "RHS Slovak Armed Forces"],	
	["ROAF_BLU", "Romanian Armed Forces"],
	["RUS_GRU", "Russian Armed Forces 2035"],
	["Ryan_ZD", "Ryan Zombies and Demons"],
	["SAF2035", "South African Armed Forces"],
	["SFP_SAF", "Swedish armed Forces"],
	["SOG_USA", "SoG Prairie Fire USA"],
	["SOG_VIETCONG", "SoG Prairie Fire VIETCONG"],
	["SPE_FFI", "SPE - FFI Force Interieur"],
	["SPE_FR", "SPE - FR Liberation Army"],
	["SPE_GER", "SPE - GER Wehrmacht"],
	["SPE_US", "SPE - USA US Army"],
	["SW_TOR", "Star Wars The Old Republic"],
	["TFM_MMSLI_W", "Milsim Light Infantry - Woodland"],
	["TFM_MSCA_D", "Milsim Combined Arms - Desert"],
	["TFM_MSCA_W", "Milsim Combined Arms - Woodland"],
	["TFM_MSLI_D", "Milsim Light Infantry - Desert"],
	["TFM_SOG_CA", "SOG US for Combined Arms"],
	["TFM_SOG_LI", "SOG US for Light Infantry"],
	["TIOW_CSP", "Chaos Space Marines"],
	["TIOW_TAU", "Tau Alliance"],
	["UA_AZOV", "Armed Forces of Ukraine"],
	["UNS_NVA", "Unsung NVA"],
	["UNS_US", "Unsung USA"],
	["VME_CHINA", "VME China Army"],
	["VTF_KDF", "Korsac Defense Force"],
	["VTF_KI","Korsac Insurgents"],
	["WBK_ORKS", "Orks"],
	["WS_FIA", "West Sahara FIA"],
	["WS_UNA", "West Sahara UNA"]
];
