// Initalize Side
GRLIB_arsenal_side = WEST;

//Blacklist Items
blacklisted_bag = [
];

blacklisted_weapon = [
	"optic_Nightstalker",
	"optic_tws",
	"optic_tws_mg",
	"NVGoggles_tna_F",
	"NVGogglesB_blk_F",
	"NVGogglesB_grn_F",
	"NVGogglesB_gry_F",
	"H_HelmetO_ViperSP_hex_F",
	"H_HelmetO_ViperSP_ghex_F",
	"U_O_V_Soldier_Viper_hex_F",
	"U_O_V_Soldier_Viper_F",
	"O_V_Soldier_Viper_F",
	"O_V_Soldier_Viper_hex_F",
	"R3F_LGI_DEM"
];

GRLIB_whitelisted_from_arsenal = [
	"1Rnd_HE_Grenade_shell",
	"3Rnd_HE_Grenade_shell",
	"30Rnd_65x39_caseless_msbs_mag",
	"2Rnd_12Gauge_Slug",
	"2Rnd_12Gauge_Pellets",
	"15Rnd_12Gauge_Slug",
	"15Rnd_12Gauge_Pellets",
	"75rnd_762x39_AK12_Mag_F",
	"arifle_AK12_F",
	"arifle_AK12_GL_F",
	"arifle_AK12_lush_F",
	"arifle_AK12_arid_F",
	"arifle_AK12U_F",
	"arifle_ARX_blk_F",
	"arifle_ARX_ghex_F",
	"arifle_ARX_hex_F",
	"arifle_RPK12_F",
	"arifle_RPK12_lush_F",
	"arifle_RPK12_arid_F",
	"arifle_MSBS65_F",
	"arifle_MSBS65_black_F",
	"arifle_MSBS65_Mark_F",
	"arifle_MSBS65_Mark_black_F",
	"arifle_MSBS65_UBS_F",
	"arifle_MSBS65_UBS_black_F",
	"arifle_SPAR_01_khk_F",
	"arifle_SPAR_01_snd_F",
	"arifle_SPAR_01_GL_khk_F",
	"arifle_SPAR_01_GL_snd_F",
	"arifle_CTAR_blk_F",
	"arifle_CTAR_GL_blk_F",
	"srifle_DMR_05_blk_F",
	"srifle_DMR_07_blk_F",
	"srifle_DMR_07_hex_F",
	"srifle_DMR_04_F",
	"srifle_DMR_04_Tan_F",
	"arifle_MXM_Black_F",
	"sgun_HunterShotgun_01_F",
	"sgun_HunterShotgun_01_sawedoff_F",
	"MMG_01_hex_F",
	"MMG_01_tan_F",
	"MMG_02_black_F",
	"LMG_03_F",
	"LMG_Mk200_black_F",
	"SMG_03_black",
	"SMG_03_TR_black",
	"SMG_03C_TR_black",
	"launch_O_Vorona_green_F",
	"launch_O_Vorona_brown_F",
	"launch_RPG32_green_F",
	"launch_RPG32_camo_F",
	"launch_MRAWS_green_F",
	"launch_MRAWS_olive_F",
	"launch_MRAWS_sand_F",
	"NVGoggles_OPFOR",
	"optic_Arco_blk_F",
	"optic_KHS_blk",
	"optic_KHS_old",
	"optic_ico_01_f",
	"optic_ico_01_black_f",
	"muzzle_snds_B",
	"muzzle_snds_B_snd_F",
	"muzzle_snds_M",
	"muzzle_snds_H_MG",
	"muzzle_snds_H_MG_blk_F",
	"muzzle_snds_58_blk_F",
	"muzzle_snds_93mmg",
	"B_Bergen_mcamo_F",
	"B_Bergen_hex_F"
];
GRLIB_whitelisted_from_arsenal_limited = [
	"launch_I_Titan_F",
	"Titan_AA",
	"launch_RPG32_green_F",
	"RPG32_F",
	"launch_MRAWS_green_F",
	"MRAWS_HEAT_F",
	"HandGrenade",
	"MiniGrenade"
];
