// *** CIVILIAN ***

// Ukraine Civilian
civilians = [
"c_civil_cloth_02",
"c_civil_cloth_03",
"c_civil_cloth_04",
"c_civil_cloth_05",
"c_civil_cloth_06",
"c_civil_cloth_07",
"c_civil_cloth_08",
"c_civil_cloth_09",
"c_civil_cloth_10",
"c_civil_cloth_11",
"c_civil_cloth_12",
"c_civil_cloth_16",
"c_civil_poloshirt_01",
"c_civil_poloshirt_02",
"c_civil_poloshirt_03",
"c_civil_poloshirt_04",
"c_uacivil_medic_red_base",
"c_civil_polopants_01",
"c_civil_polopants_02",
"c_civil_polopants_03",
"c_civil_polopants_04",
"c_civil_formalsuit_vyshiv_01",
"c_civil_volunteer_01",
"c_civil_volunteer_02",
"c_civil_volunteer_03",
"c_civil_volunteer_04",
"c_civil_volunteer_05",
"c_civil_volunteer_06",
"c_civil_volunteer_07",
"c_civil_volunteer_08",
"c_civil_volunteer_09",
"c_civil_volunteer_10",
"c_civil_volunteer_11",
"c_civil_volunteer_13"
];

civilian_vehicles = [
	"C_Plane_Civil_01_F",	
	"C_Heli_light_01_sheriff_F",
	"C_Heli_Light_01_civil_F",
	"C_Heli_light_01_furious_F",
	"C_Offroad_01_F",
	"C_Offroad_01_darkred_F",
	"C_Offroad_luxe_F",
	"C_Offroad_02_unarmed_F",
	"C_Offroad_01_covered_F",
	"C_Offroad_01_comms_F",
	"I_C_Offroad_02_unarmed_F",
	"C_Quadbike_01_F",
	"SUV_01_base_black_F",
	"C_SUV_01_F",
	"C_Van_01_transport_F",
	"C_Van_01_box_F",
	"C_Van_01_fuel_F",
	"C_Quadbike_01_F",
	"C_Van_02_transport_F",
	"C_Van_02_medevac_F",
	"C_Van_02_service_F",
	"B_GEN_Van_02_transport_F",
	"C_Truck_02_covered_F",
	"C_Truck_02_transport_F",
	"C_Tractor_01_F",
	// RHS
	"RHS_Ural_Civ_01",
	"RHS_Ural_Open_Civ_01",
	"RHS_Ural_Civ_02",
	"RHS_Ural_Open_Civ_02",
	"RHS_Ural_Civ_03",
	"RHS_Ural_Open_Civ_03",
	"RHS_Mi8amt_civilian",
	"RHS_Mi8t_civilian",
	// Ukraine
	"c_uadsns_offroad_expl01",
	"c_uadsns_offroad_emergency01",
	"c_civil_ambulance_01",
	"c_uacivil_van01_01",
	"c_cimic_medevac_van"
];
