//Blacklist Items
blacklisted_bag = [
];

blacklisted_weapon = [
	'_Pod_',
	"CUP_PylonPod_",
	"CUP_optic_CWS",
	"CUP_optic_AN_PAS_13c1",
	"CUP_optic_AN_PAS_13c2",
	"CUP_optic_GOSHAWK",
	"CUP_optic_GOSHAWK_RIS",
	"CUP_Item_optic_AN_PAS_13c2",
	"CUP_Item_optic_AN_PAS_13c1"
];

whitelisted_from_arsenal = [
// PLA - People's Liberation Army
// Uniform
"PLA_Combat_Uniform_Arid",
"PLA_Combat_Uniform_Rolled_Arid",
"PLA_Combat_Uniform_Navy",
"PLA_Combat_Uniform_Rolled_Navy",
"PLA_Combat_Uniform",
"PLA_Combat_Uniform_Rolled",
// Vest
"PLA_V_CarrierRigKBT_01_light_Navy_F",
"PLA_V_CarrierRigKBT_01_heavy_Navy_F",
"PLA_Vest_Grenadier_Arid",
"PLA_Vest_Machinegunner_Arid",
"PLA_Vest_Rifleman_Arid",
"PLA_Vest_Grenadier_Wood",
"PLA_Vest_Machinegunner_Wood",
"PLA_Vest_Rifleman_Wood",
// Backpack
"PLA_Arid_Backpack_Compact",
"PLA_Backpack_Compact_Navy",
"Flex_CUP_PLA_pack_mg",
"PLA_Backpack_Compact",
"PLA_Arid_Backpack",
"PLA_Navy_Backpack",
"PLA_Backpack",
"PLA_Arid_Radio_Backpack",
"PLA_Radio_Backpack_Navy",
"PLA_Radio_Backpack",
//Headgear
"PLA_Arid_Patrol_cap",
"PLA_Patrol_cap_Navy",
"PLA_Patrol_cap",
"PLA_H_Arid_Helmet01",
"PLA_H_Arid_Helmet02",
"PLA_H_Helmet01_Navy",
"PLA_H_Helmet02_Navy",
"PLA_H_Helmet01",
"PLA_H_Helmet02",
"PLA_Arid_Opscore_SF",
"PLA_Opscore_SF_Navy",
"PLA_Opscore_SF",
//Googles
"PLA_Balaclava_Alt_Olive",
"PLA_Balaclava_Alt_1_Olive",
"PLA_Balaclava_Alt_Tan",
"PLA_Balaclava_Alt_1_Tan",
"PLA_Balaclava_Alt_Black",
"PLA_Balaclava_Alt_1_Black",
"hgun_Rook40_F",
"16Rnd_9x21_Mag",
"arifle_CTAR_blk_F",
"30Rnd_580x42_Mag_F",

// UTL
	"FirstAidKit",
	"Medikit",
	"ToolKit",
	"MineDetector",
	"Binocular",
	"Rangefinder",
	"ItemCompass",
	"ItemGPS",
	"ItemMap",
	"ItemRadio",
	"ItemWatch",
	"Bandage",
	"HandGrenade",
	"MiniGrenade",
	//"Laserbatteries",
	//"APERSMine_Range_Mag",
	//"APERSBoundingMine_Range_Mag",
	"ATMine_Range_Mag",
	"SatchelCharge_Remote_Mag",
	"SLAMDirectionalMine_Wire_Mag",
// Z@Warrior
"optic_Aco",
"optic_Arco",
"optic_LRPS",
"optic_Holosight",
"optic_SOS",
"optic_MRCO",
"optic_Hamr",
"muzzle_snds_M",
"muzzle_snds_B",
"muzzle_snds_B_khk_F",
"acc_pointer_IR",
"acc_flashlight",
"bipod_01_F_khk",
"bipod_02_F_blk",
"bipod_01_F_blk",
// Granaten
"SmokeShellBlue",
"SmokeShellYellow",
"SmokeShellGreen",
"SmokeShellOrange",
"SmokeShellRed",
"SmokeShellPurple",
"SmokeShell",
"Chemlight_red",
"Chemlight_green",
"Chemlight_yellow",
"Chemlight_blue",
"1Rnd_HE_Grenade_shell",
// Sprengmittel
"DemoCharge_Remote_Mag",
"APERSMine_Range_Mag",
"ClaymoreDirectionalMine_Remote_Mag",
// under Water equipment
"U_B_Wetsuit",
"V_RebreatherB",
"G_B_Diving",
"arifle_SDAR_F",
"20Rnd_556x45_UW_mag"
];